# Site settings
course_name: Natural Language Processing - A Machine Learning Perspective
course_description: "The series of Natural Language Processing Online Course are the corresponding Chinese course videos of the book, Natural Language Processing: A Machine Learning Perspective. Professor Yue Zhang is a principal inverstigator of Text Intelligence Lab, Westlake University, and a well-known NLP researcher. You may find more detailed information at his personal page or Google Scholar. Currently, the courses are updataed by our bilibili account, WestlakeNLP. We appreciate your following! In this page, we will keep updating course slides."
course_semester: "Fall 2021"

baseurl: "/jekyll-course-website-template" # the subpath of your site, e.g. /blog/
url: "https://bimunlp.github.io" # the base hostname & protocol for your site

schoolname: "Westlake University"
schoolurl: "https://westlake.edu.cn"
twitter_username: NlpWestlake

address: |
    School of Engineering
    Westlake University
    Hangzhou
    Zhejiang
    China
# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
